# Generated by Django 5.1.4 on 2025-01-15 16:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ebooks_app', '0002_order_razorpay_payment_id_order_receipt_id_orderitem_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderitem',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order_items', to='ebooks_app.order'),
        ),
    ]
